[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ran"
authors = [{name = "Graziella", email = "ran_chen_1@nxp"}]
dynamic = ["version", "description"]
